######################################################################
# Automatically generated by qmake (2.01a) jeu. mai 17 10:13:44 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fenetreprincipale.h \
    aboutdepannage.h
FORMS += fenetreprincipale.ui \
    aboutdepannage.ui
SOURCES += fenetreprincipale.cpp main.cpp \
    aboutdepannage.cpp

RESOURCES += \
    resources.qrc
